# Generated by Django 4.0.4 on 2022-05-06 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_check', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
